version: '3.8'

# 通过环境变量指定要部署的环境
# 使用方法：ENV=test docker-compose up -d
# 默认为production环境

services:
  ryu-web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BUILD_ENV=${ENV:-production}
    container_name: ryu-web-${ENV:-production}
    ports:
      - "${PORT:-80}:80"
    restart: unless-stopped
    env_file:
      - .env.${ENV:-production}
    environment:
      - APP_ENV=${ENV:-production}
    volumes:
      # 挂载nginx日志目录
      - ./logs:/var/log/nginx
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

networks:
  app-network:
    driver: bridge 